CREATE TABLE IF NOT EXISTS students (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  student_id VARCHAR(50) NOT NULL UNIQUE,
  course VARCHAR(255) NOT NULL,
  documents INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);